[package]
name = "Surf-Rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "cli",
    "core",
    "lexer",
    "shared",
    "checker",
    "c_parser",
    "extractor",
    "logger"
]

[dependencies]
cli = { path = "cli" }