[package]
name = "Surf-Rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "cli",
    "core",
    "lexer",
    "shared",
    "checker",
    "parser",
    "extractor"
]

[dependencies]
cli = { path = "cli" }
parser = { path = "parser" }