[package]
name = "cli"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"]}
shared = { path = "../shared" }
fancy-regex = "0.14.0"
lazy_static = "1.5.0"
serde = {version = "1.0.215", features = ["derive"]}
serde_yml = "0.0.12"
emojis = "0.6.4"