[package]
name = "extractor"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
lexer = { path = "../lexer" }
logger = { path = "../logger" }
util = { path = "../util" }
code = { path = "../code" }