[package]
name = "core"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
lexer = { path = "../lexer" }
extractor = { path = "../extractor" }
fancy-regex = "0.14.0"
lazy_static = "1.5.0"
code = { path = "../code" }