[package]
name = "shared"
edition = "2021"

[dependencies]
fancy-regex = "0.14.0"
lazy_static = "1.5.0"
inquire = "0.7.5"
clang = "2.0.0"
c_parser = { path = "../c_parser" }
logger = { path = "../logger" }